# this is a YAML-formatted file
# declare variables to be passed into your templates

deploymentName: eurekaserver-deployment
serviceName: eurekaserver
appLabel: eurekaserver
appName: eurekaserver

replicaCount: 1

image:
  repository: pushnofear/eurekaserver
  tag: s14

containerPort: 8070

service:
  type: ClusterIP
  port: 8070
  targetPort: 8070

app_name_enabled: true
profile_enabled: false
config_enabled: true
eureka_enabled: false
resource_server_enabled: false
otel_enabled: true
kafka_enabled: false
