services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      timeout: 10s
      retries: 10
    extends:
      file: common-config.yml
      service: network-deploy-service

  configserver:
    image: "pushnofear/configserver:s10"
    container_name: configserver-ms
    ports:
      - "8071:8071"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8071/actuator/health/readiness"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config

  eurekaserver:
    image: "pushnofear/eurekaserver:s10"
    container_name: eurekaserver-ms
    ports:
      - "8070:8070"
    volumes:
      - "../dockerize:/usr/local/bin/dockerize:ro"
    entrypoint:
      - /usr/local/bin/dockerize
      - -wait
      - http://configserver:8071/actuator/health/readiness
      - -timeout
      - 60s
      - /cnb/process/web
    environment:
      SPRING_APPLICATION_NAME: "eurekaserver"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8070/actuator/health/readiness"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config

  accounts:
    image: "pushnofear/accounts:s10"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health/readiness"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    volumes:
      - "../dockerize:/usr/local/bin/dockerize:ro"
    entrypoint:
      - /usr/local/bin/dockerize
      - -wait
      - http://configserver:8071/actuator/health/readiness
      - -wait
      - http://eurekaserver:8070/actuator/health/readiness
      - -timeout
      - 90s
      - /cnb/process/web
    environment:
      SPRING_APPLICATION_NAME: "accounts"
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  loans:
    image: "pushnofear/loans:s10"
    container_name: loans-ms
    ports:
      - "8090:8090"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8090/actuator/health/readiness"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    volumes:
      - "../dockerize:/usr/local/bin/dockerize:ro"
    entrypoint:
      - /usr/local/bin/dockerize
      - -wait
      - http://configserver:8071/actuator/health/readiness
      - -wait
      - http://eurekaserver:8070/actuator/health/readiness
      - -timeout
      - 90s
      - /cnb/process/web
    environment:
      SPRING_APPLICATION_NAME: "loans"
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  cards:
    image: "pushnofear/cards:s10"
    container_name: cards-ms
    ports:
      - "9000:9000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/actuator/health/readiness"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    volumes:
      - "../dockerize:/usr/local/bin/dockerize:ro"
    entrypoint:
      - /usr/local/bin/dockerize
      - -wait
      - http://configserver:8071/actuator/health/readiness
      - -wait
      - http://eurekaserver:8070/actuator/health/readiness
      - -timeout
      - 90s
      - /cnb/process/web
    environment:
      SPRING_APPLICATION_NAME: "cards"
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  gatewayserver:
    image: "pushnofear/gatewayserver:s10"
    container_name: gatewayserver-ms
    ports:
      - "8072:8072"
    volumes:
      - "../dockerize:/usr/local/bin/dockerize:ro"
    entrypoint:
      - /usr/local/bin/dockerize
      - -wait
      - http://accounts:8080/actuator/health/readiness
      - -wait
      - http://loans:8090/actuator/health/readiness
      - -wait
      - http://cards:9000/actuator/health/readiness
      - -wait
      - tcp://redis:6379
      - -timeout
      - 120s
      - /cnb/process/web
    environment:
      SPRING_APPLICATION_NAME: "gatewayserver"
      SPRING_DATA_REDIS_CONNECT-TIMEOUT: 2s
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_DATA_REDIS_TIMEOUT: 1s
    extends:
      file: common-config.yml
      service: microservice-eureka-config

networks:
  eazybank:
    driver: "bridge"
